export const locationData = [
    {
      id: 1,
      names: ['N0', 'East Gate'],
      latitude: null,
      longitude: null,
    },
    {
      id: 2,
      names: ['N1', 'Kim Beang-Ho & Kim Sam-Youl ITC Building'],
      latitude: null,
      longitude: null,
    },
    {
      id: 3,
      names: ['N2', 'Branch Administration B/D'],
      latitude: null,
      longitude: null,
    },
    {
      id: 4,
      names: ['N3', 'Sports Complex'],
      latitude: null,
      longitude: null,
    },
    {
      id: 5,
      names: ['N4', 'School of Humanities & Social Science B/D', 'Language Center'],
      latitude: null,
      longitude: null,
    },
    {
      id: 6,
      names: ['N5', 'Convergence Research B/D'],
      latitude: null,
      longitude: null,
    },
    {
      id: 7,
      names: ['N6', 'Faculty Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 8,
      names: ['N7', 'Mechanical Engineering B/D'],
      latitude: null,
      longitude: null,
    },
    {
      id: 9,
      names: ['N7-1', 'Dept. of Nuclear & Quantum Engineering'],
      latitude: null,
      longitude: null,
    },
    {
      id: 10,
      names: ['N7-2', 'Dept. of Aerospace Engineering'],
      latitude: null,
      longitude: null,
    },
    {
      id: 11,
      names: ['N7-3 / N7-4', 'Dept. of Mechanical Engineering'],
      latitude: null,
      longitude: null,
    },
    {
      id: 12,
      names: ['N7-5', 'Automobile Technology Laboratory Building'],
      latitude: null,
      longitude: null,
    },
    {
      id: 13,
      names: ['N9', 'Practice B/D'],
      latitude: null,
      longitude: null,
    },
    {
      id: 14,
      names: ['N10', 'Undergraduate Branch Library'],
      latitude: null,
      longitude: null,
    },
    {
      id: 15,
      names: ['N11', 'Cafeteria'],
      latitude: null,
      longitude: null,
    },
    {
      id: 16,
      names: ['N12', 'Student Center-2'],
      latitude: null,
      longitude: null,
    },
    {
      id: 17,
      names: ['N13', 'Tae Wul Gwan'],
      latitude: null,
      longitude: null,
    },
    {
      id: 18,
      names: ['N13-1', 'Chang Young Shin Student Center'],
      latitude: null,
      longitude: null,
    },
    {
      id: 19,
      names: ['N14', 'Sarang Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 20,
      names: ['N15', 'Staff Accommodation'],
      latitude: null,
      longitude: null,
    },
    {
      id: 21,
      names: ['N16', 'Somang Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 22,
      names: ['N17', 'Seongsil Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 23,
      names: ['N18', 'Jilli Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 24,
      names: ['N19', 'Areum Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 25,
      names: ['N20', 'Silloe Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 26,
      names: ['N21', 'Jihye Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 27,
      names: ['N22', 'Alumni Venture Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 28,
      names: ['N23', 'fMRI Center'],
      latitude: null,
      longitude: null,
    },
    {
      id: 29,
      names: ['N24', 'LG Innovation Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 30,
      names: ['N25', 'Dept. of Industrial Design B/D'],
      latitude: null,
      longitude: null,
    },
    {
      id: 31,
      names: ['N26', 'Center for High-Performance Integrated Syetems'],
      latitude: null,
      longitude: null,
    },
    {
      id: 32,
      names: ['N27', 'Eureka Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 33,
      names: ['N28', 'Energy & Environment Research Center'],
      latitude: null,
      longitude: null,
    },
    {
      id: 34,
      names: ['E1', 'Main Gate'],
      latitude: null,
      longitude: null,
    },
    {
      id: 35,
      names: ['E2', 'Industrial Engineering & Management B/D'],
      latitude: null,
      longitude: null,
    },
    {
      id: 36,
      names: ['E2-1', 'Dept. of Mathematical Sciences'],
      latitude: null,
      longitude: null,
    },
    {
      id: 37,
      names: ['E2-2', 'Dept. of Industrial & Systems Engineering', 'Graduate School of Knowledge Service Engineering'],
      latitude: null,
      longitude: null,
    },
    {
      id: 38,
      names: ['E3', 'Information & Electronics B/D'],
      latitude: null,
      longitude: null,
    },
    {
      id: 39,
      names: ['E3-1', 'School of Computing'],
      latitude: null,
      longitude: null,
    },
    {
      id: 40,
      names: ['E3-2', 'School of Electrical Engineering'],
      latitude: null,
      longitude: null,
    },
    {
      id: 41,
      names: ['E3-3', 'Device Innovation Facility'],
      latitude: null,
      longitude: null,
    },
    {
      id: 42,
      names: ['E3-4', 'Saeneul Dong'],
      latitude: null,
      longitude: null,
    },
    {
      id: 43,
      names: ['E4', 'KAIST Institutes B/D'],
      latitude: null,
      longitude: null,
    },
    {
      id: 44,
      names: ['E5', 'Faculty Club'],
      latitude: null,
      longitude: null,
    },
    {
      id: 45,
      names: ['E6', 'Natural Science B/D'],
      latitude: null,
      longitude: null,
    },
    {
      id: 46,
      names: ['E6-1', 'Dept. of Mathematical Sciences'],
      latitude: null,
      longitude: null,
    },
    {
      id: 47,
      names: ['E6-2', 'Dept. of Physics'],
      latitude: null,
      longitude: null,
    },
    {
      id: 48,
      names: ['E6-3', 'Dept. of Biological Sciences'],
      latitude: null,
      longitude: null,
    },
    {
      id: 49,
      names: ['E6-4', 'Dept. of Chemistry'],
      latitude: null,
      longitude: null,
    },
    {
      id: 50,
      names: ['E6-5', 'GoongNi Laboratory Building'],
      latitude: null,
      longitude: null,
    },
    {
      id: 51,
      names: ['E6-6', 'Basic Science Building'],
      latitude: null,
      longitude: null,
    },
    {
      id: 52,
      names: ['E7', 'Biomedical Research Center'],
      latitude: null,
      longitude: null,
    },
    {
      id: 53,
      names: ['E8', 'Sejong Hall'],
      latitude: null,
      longitude: null,
    },
    {
      id: 54,
      names: ['E9', 'Academic Cultural Complex'],
      latitude: null,
      longitude: null,
    },
    {
      id: 55,
      names: ['E10', 'Storehouse'],
      latitude: null,
      longitude: null,
    },
    {
      id: 56,
      names: ['E11', 'Creative Learning B/D', 'Office of Admissions', 'Office of Student Affairs & Policy', 'Office of Student Life'],
      latitude: null,
      longitude: null,
    },
    {
      id: 57,
      names: ['E12', 'Energy Plant'],
      latitude: null,
      longitude: null,
    },
    {
      id: 58,
      names: ['E13', 'Satellite Technology Research Center'],
      latitude: null,
      longitude: null,
    },
  {
    id: 59,
    names: ['E14', 'Main Administration B/D', 'Office of Academic Affairs', 'Office of Research Affairs', 'Office of Planning and Budget', 'Office of Administration'],
    latitude: null,
    longitude: null,
  },
  {
    id: 60,
    names: ['E15', 'Auditorium'],
    latitude: null,
    longitude: null,
  },
  {
    id: 61,
    names: ['E16', 'ChungMoonSoul B/D'],
    latitude: null,
    longitude: null,
  },
  {
    id: 62,
    names: ['E16-1', 'YANG Bun Soon B/D', 'Office of Admissions', 'Dept. of Bio and Brain Engineering'],
    latitude: null,
    longitude: null,
  },
  {
    id: 63,
    names: ['E17', 'Stadium'],
    latitude: null,
    longitude: null,
  },
  {
    id: 64,
    names: ['E18', 'Daejeon Disease-model Animal Center'],
    latitude: null,
    longitude: null,
  },
  {
    id: 65,
    names: ['E18-1', 'Bio Model System Park'],
    latitude: null,
    longitude: null,
  },
  {
    id: 66,
    names: ['E19', 'National Nano Fab Center'],
    latitude: null,
    longitude: null,
  },
  {
    id: 67,
    names: ['E20', 'Kyeryong Hall'],
    latitude: null,
    longitude: null,
  },
  {
    id: 68,
    names: ['E21', 'KAIST Clinic', 'Pharmacy'],
    latitude: null,
    longitude: null,
  },
  {
    id: 69,
    names: ['W1', 'Applied Engineering B/D'],
    latitude: null,
    longitude: null,
  },
  {
    id: 70,
    names: ['W1-1', 'Dept. of Materials Science & Engineering'],
    latitude: null,
    longitude: null,
  },
  {
    id: 71,
    names: ['W1-2', 'Dept. of Civil & Environmental Engineering'],
    latitude: null,
    longitude: null,
  },
  {
    id: 72,
    names: ['W1-3', 'Dept. of Chemical & Biomolecular Engineering'],
    latitude: null,
    longitude: null,
  },
  {
    id: 73,
    names: ['W2', 'Student Center-1'],
    latitude: null,
    longitude: null,
  },
  {
    id: 74,
    names: ['W2-1', 'International Center'],
    latitude: null,
    longitude: null,
  },
  {
    id: 75,
    names: ['W3', 'Galilei Hall'],
    latitude: null,
    longitude: null,
  },
  {
    id: 76,
    names: ['W4-1', 'Yeoul Hall'],
    latitude: null,
    longitude: null,
  },
  {
    id: 77,
    names: ['W4-2', 'Nadl Hall'],
    latitude: null,
    longitude: null,
  },
  {
    id: 78,
    names: ['W4-3', 'Dasom Hall'],
    latitude: null,
    longitude: null,
  },
  {
    id: 79,
    names: ['W4-4', 'Heemang Hall'],
    latitude: null,
    longitude: null,
  },
  {
    id: 80,
    names: ['W5-1', 'Yeji Hall'],
    latitude: null,
    longitude: null,
  },
  {
    id: 81,
    names: ['W5-2', 'Startup Village'],
    latitude: null,
    longitude: null,
  },
  {
    id: 82,
    names: ['W5-3', 'International Village C'],
    latitude: null,
    longitude: null,
  },
  {
    id: 83,
    names: ['W5-4', 'International Village A'],
    latitude: null,
    longitude: null,
  },
  {
    id: 84,
    names: ['W5-5', 'International Village B'],
    latitude: null,
    longitude: null,
  },
  {
    id: 85,
    names: ['W6', 'Mir Hall', 'Narae Hall'],
    latitude: null,
    longitude: null,
  },
  {
    id: 86,
    names: ['W7', 'Nanum Hall'],
    latitude: null,
    longitude: null,
  },
  {
    id: 87,
    names: ['W8', 'Educational Support B/D'],
    latitude: null,
    longitude: null,
  },
  {
    id: 88,
    names: ['W8-1', 'Analysis Center for Research Advancement'],
    latitude: null,
    longitude: null,
  },
  {
    id: 89,
    names: ['W8-3', 'KAIHELP'],
    latitude: null,
    longitude: null,
  },
  {
    id: 90,
    names: ['W9', 'Outdoor Theater'],
    latitude: null,
    longitude: null,
  },
  {
    id: 91,
    names: ['W10', 'Wind Tunnel Laboratory'],
    latitude: null,
    longitude: null,
  },
  {
    id: 92,
    names: ['W11', 'International Faculty Apartment'],
    latitude: null,
    longitude: null,
  },
  {
    id: 93,
    names: ['W12', 'West Energy Plant'],
    latitude: null,
    longitude: null,
  },
  {
    id: 94,
    names: ['W16', 'Geotechnical Centrifuge Testing Center'],
    latitude: null,
    longitude: null,
  },
];

export default locationData;